import type { DepRule } from '../types.ts';

/**
 * Dependency-manifest knowledge base — a port of shorproof v0.0.1's curated
 * package list, expressed as typed rule data.
 *
 * IMPORTANT: the `why` and `migration` strings are copied verbatim from v0.0.1
 * (they were `reason` / `hint` there). A parity test executes the legacy
 * bin/shorproof.js against the new CLI and asserts equivalence, so do not reword
 * these without intentionally updating that baseline.
 *
 * A manifest match only proves a package is *present*, not that it is used with
 * a quantum-vulnerable algorithm — hence confidence is `medium` for vulnerable
 * entries (the AST scanner is what upgrades a hunch to a usage-confirmed
 * finding). Severities preserve v0.0.1 behaviour.
 */
export const DEP_RULES = [
  {
    id: 'deps/jsonwebtoken',
    package: 'jsonwebtoken',
    title: 'jsonwebtoken — JWT signing/verification',
    severity: 'high',
    category: 'signature',
    algorithm: 'RSA/ECDSA',
    confidence: 'medium',
    lifetimeSensitive: false,
    why: 'JWTs are typically signed with RS256/ES256 (RSA/ECDSA) — breakable by Shor’s algorithm.',
    migration: 'Review your alg choices. ML-DSA (post-quantum) signing exists in `jose` and Node 24.7+.',
  },
  {
    id: 'deps/node-rsa',
    package: 'node-rsa',
    title: 'node-rsa — RSA key generation/encryption/signing',
    severity: 'high',
    category: 'signature',
    algorithm: 'RSA',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'RSA key generation/encryption/signing — directly breakable by Shor’s algorithm.',
    migration: 'Plan migration to ML-KEM (encryption) / ML-DSA (signatures) or hybrid schemes.',
  },
  {
    id: 'deps/jsrsasign',
    package: 'jsrsasign',
    title: 'jsrsasign — RSA/ECDSA signing and X.509 tooling',
    severity: 'high',
    category: 'signature',
    algorithm: 'RSA/ECDSA',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'RSA/ECDSA signing and X.509 tooling — classical asymmetric crypto throughout.',
    migration: 'Inventory where certificates/signatures produced here have a long lifetime.',
  },
  {
    id: 'deps/ursa',
    package: 'ursa',
    title: 'ursa — RSA library (unmaintained)',
    severity: 'high',
    category: 'signature',
    algorithm: 'RSA',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'RSA-only library (also long unmaintained).',
    migration: 'Migrate off — both for quantum readiness and basic maintenance risk.',
  },
  {
    id: 'deps/elliptic',
    package: 'elliptic',
    title: 'elliptic — ECDSA/ECDH primitives',
    severity: 'medium',
    category: 'signature',
    algorithm: 'ECC',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Elliptic-curve cryptography (ECDSA/ECDH) — quantum-vulnerable via Shor’s algorithm.',
    migration: 'Check what depends on it and whether signatures/keys outlive the quantum timeline.',
  },
  {
    id: 'deps/tweetnacl',
    package: 'tweetnacl',
    title: 'tweetnacl — Ed25519/X25519 signing and key exchange',
    severity: 'medium',
    category: 'signature',
    algorithm: 'Ed25519/X25519',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Ed25519/X25519 (elliptic-curve) signatures and key exchange — quantum-vulnerable.',
    migration: 'Fine for short-lived operations today; plan hybrid (ECC + PQC) for anything long-lived.',
  },
  {
    id: 'deps/libsodium-wrappers',
    package: 'libsodium-wrappers',
    title: 'libsodium-wrappers — Ed25519/X25519 primitives',
    severity: 'medium',
    category: 'signature',
    algorithm: 'Ed25519/X25519',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Ed25519/X25519 based signing and key exchange — quantum-vulnerable primitives.',
    migration: 'Plan hybrid (ECC + ML-KEM/ML-DSA) for long-lived data or signatures.',
  },
  {
    id: 'deps/@noble/curves',
    package: '@noble/curves',
    title: '@noble/curves — elliptic-curve primitives',
    severity: 'medium',
    category: 'signature',
    algorithm: 'ECC',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Elliptic-curve primitives — quantum-vulnerable via Shor’s algorithm.',
    migration: 'Same author ships @noble/post-quantum with hybrid constructions — natural migration path.',
  },
  {
    id: 'deps/@noble/ed25519',
    package: '@noble/ed25519',
    title: '@noble/ed25519 — Ed25519 signatures',
    severity: 'medium',
    category: 'signature',
    algorithm: 'Ed25519',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Ed25519 signatures (elliptic-curve) — quantum-vulnerable.',
    migration: 'Consider hybrid signing for long-lived artifacts.',
  },
  {
    id: 'deps/@noble/secp256k1',
    package: '@noble/secp256k1',
    title: '@noble/secp256k1 — secp256k1 signatures',
    severity: 'medium',
    category: 'signature',
    algorithm: 'secp256k1',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'secp256k1 (elliptic-curve) — quantum-vulnerable.',
    migration: 'Relevant mostly if keys/signatures must stay valid for many years.',
  },
  {
    id: 'deps/openpgp',
    package: 'openpgp',
    title: 'openpgp — RSA/ECC key material',
    severity: 'medium',
    category: 'kem',
    algorithm: 'RSA/ECC',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'OpenPGP uses RSA/ECC key material — encrypted data is exposed to harvest-now-decrypt-later.',
    migration: 'Long-retention encrypted archives are the priority to re-protect.',
  },
  {
    id: 'deps/ssh2',
    package: 'ssh2',
    title: 'ssh2 — SSH host/user keys',
    severity: 'review',
    category: 'key-exchange',
    algorithm: 'RSA/ECDSA/Ed25519',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'SSH host/user keys are typically RSA or ECDSA/Ed25519 (classical asymmetric).',
    migration: 'Key rotation policy matters more than the library itself.',
  },
  {
    id: 'deps/node-forge',
    package: 'node-forge',
    title: 'node-forge — TLS/RSA/X.509 toolkit',
    severity: 'review',
    category: 'signature',
    algorithm: 'RSA/ECC',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'General-purpose TLS/RSA/X.509 toolkit — most common uses involve classical asymmetric crypto.',
    migration: 'Identify which forge features you actually use.',
  },
  {
    id: 'deps/jose',
    package: 'jose',
    title: 'jose — JWS/JWE/JWT (classical + PQC)',
    severity: 'review',
    category: 'signature',
    algorithm: 'RSA/ECDSA or ML-DSA',
    confidence: 'medium',
    lifetimeSensitive: false,
    why: 'Supports both classical algs (RS256/ES256 — vulnerable) and post-quantum ML-DSA (RFC 9964).',
    migration: 'You’re on the right library — check which `alg` values you actually use.',
  },
  {
    id: 'deps/jwk-to-pem',
    package: 'jwk-to-pem',
    title: 'jwk-to-pem — JWK to PEM conversion',
    severity: 'review',
    category: 'signature',
    algorithm: 'RSA/EC',
    confidence: 'medium',
    lifetimeSensitive: false,
    why: 'Converts JWKs — usually RSA/EC key material in classical formats.',
    migration: 'Signals classical asymmetric keys in your pipeline; trace where they’re used.',
  },
  {
    id: 'deps/crypto-js',
    package: 'crypto-js',
    title: 'crypto-js — symmetric crypto (AES)',
    severity: 'review',
    category: 'symmetric',
    algorithm: 'AES',
    confidence: 'medium',
    lifetimeSensitive: true,
    why: 'Mostly symmetric crypto (AES — quantum-resilient at 256-bit), but check key sizes and modes.',
    migration: 'AES-128 → prefer AES-256 for long-lived data (Grover’s algorithm halves effective strength).',
  },
  {
    id: 'deps/bcrypt',
    package: 'bcrypt',
    title: 'bcrypt — password hashing',
    severity: 'safe',
    category: 'hash',
    algorithm: 'bcrypt',
    confidence: 'high',
    lifetimeSensitive: false,
    why: 'Password hashing — not affected by Shor’s algorithm.',
    migration: '',
  },
  {
    id: 'deps/bcryptjs',
    package: 'bcryptjs',
    title: 'bcryptjs — password hashing',
    severity: 'safe',
    category: 'hash',
    algorithm: 'bcrypt',
    confidence: 'high',
    lifetimeSensitive: false,
    why: 'Password hashing — not affected by Shor’s algorithm.',
    migration: '',
  },
  {
    id: 'deps/argon2',
    package: 'argon2',
    title: 'argon2 — password hashing',
    severity: 'safe',
    category: 'hash',
    algorithm: 'argon2',
    confidence: 'high',
    lifetimeSensitive: false,
    why: 'Password hashing — not affected by Shor’s algorithm.',
    migration: '',
  },
  {
    id: 'deps/@noble/post-quantum',
    package: '@noble/post-quantum',
    title: '@noble/post-quantum — NIST PQC algorithms',
    severity: 'safe',
    category: 'kem',
    algorithm: 'ML-KEM/ML-DSA/SLH-DSA',
    confidence: 'high',
    lifetimeSensitive: false,
    why: 'ML-KEM / ML-DSA / SLH-DSA — NIST post-quantum algorithms. Good.',
    migration: '',
  },
] as const satisfies readonly DepRule[];
